### PR TITLE
WIP: Optimize scroll user experience

### PR DESCRIPTION
**Pull request by 0xfeedface1993**
Just a little work.

https://github.com/0xfeedface1993/iChatGPT/blob/main/iChatGPT/Document/Scroll-Stick.gif

- Custom scrollView. done
- Stick bottom when user at bottom  no matter container frame change or not. done
- Bouncing back like ScrollView with UIDynamic (working on it)
- Color、padding、style...etc (working on it)

### CODE REVIEW

**Comment by iHTCboy** [comment]
👋
Thank you for submitting PR~

**Comment by iHTCboy** [comment]
@0xfeedface1993 Thanks for the submission. After merging, I found that when the iPad is rotated, there is also a problem with the adaptation. I haven’t released a new version yet. I will update the version after it is completed. Thank you again for your submission and look forward to perfection~

感谢提交，合并后发现 iPad 旋转时，适配也有问题，暂时还没有对外发新版本，等完善后在更新版本，再次感谢你的提交，期待完善~

**Comment by iHTCboy** [comment]
> Unexpected bounce animate after rotated?

Yes, the iPhone horizontal screen is also reproduced.

是的，iPhone 横屏也复现了。

**Comment by 0xfeedface1993** [comment]
> > Unexpected bounce animate after rotated?
> 
> 
> 
> Yes, the iPhone horizontal screen is also reproduced.
> 
> 
> 
> 是的，iPhone 横屏也复现了。

it seems bug of TextField avoidance feature in SwiftUI, working on it.

**Pull request merged**
